buildscript {
    ext.ktor_version = '3.2.0'
}

plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
}

version '1.0-SNAPSHOT'

mainClassName = 'ScrabbleServKt'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

kotlin {
    jvmToolchain(25)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "io.ktor:ktor-server-netty:$ktor_version"
    implementation "io.ktor:ktor-server-content-negotiation:$ktor_version"
    implementation "io.ktor:ktor-server-call-logging:$ktor_version"
    implementation "io.ktor:ktor-serialization-gson:$ktor_version"
    implementation "com.google.code.gson:gson:2.12.1"
    implementation "ch.qos.logback:logback-classic:1.5.18"
    testImplementation "org.jetbrains.kotlin:kotlin-test"
}


jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': 'ScrabbleServKt'
    }

    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}
